<a href="https://colab.research.google.com/github/ridersw/Complete-Machine-Learning/blob/main/Tensorflow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x # specifies the version of Tensorflow

import tensorflow as tf
print(tf.version)

# What are Tensors and how to create tensors?
-> Tensors are basically a vectors generalised to the higher dimensions. Vectors are the data points with more than 1 value, multiple dimensions. Like Velocity that has speed and distance.

Syntax to create Vector-

{variable_name} = tf.Variable({data}, {data_type})

In [7]:
string = tf.Variable("Hello", tf.string)
integer = tf.Variable(1234, tf.int32)
floating = tf.Variable(1.234, tf.float32)
array = tf.Variable(['Hello', 'my'], tf.string)
array2d = tf.Variable([['this', 'is'],['kinda', 'new']], tf.string)

print(f'string: {string}')
print(f'integer: {integer}')
print(f'floating: {floating}')
print(f'array: {array}')
print(f'array2d: {array2d}')

string: <tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hello'>
integer: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1234>
floating: <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.234>
array: <tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'Hello', b'my'], dtype=object)>
array2d: <tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'this', b'is'],
       [b'kinda', b'new']], dtype=object)>


# What is Rank/ Degree of Tensor?
-> It is the dimension of the tensor 

In [10]:
tf.rank(array2d)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# What is Shape of the Tensor?
-> It is the count of elements in each dimension

In [13]:
array.shape

TensorShape([2])

# Shape of Tensor

In [16]:
array = tf.ones([1,2,3])

print(f'array: {array}')

#change shape
newArray = tf.reshape(array, [2,3,1])

print(f'newArray: {newArray}')

array: [[[1. 1. 1.]
  [1. 1. 1.]]]
newArray: [[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
